### ISSUE TITLE
How to adapt & debug your azure function app?

### ISSUE THREAD

**Issue by fbka** [rebremer/azure-function-selenium#1]
Thank you so much for sharing your work. 

With some adjustments I was able to successfully replicate your setup and use the http_trigger to crawl http://www.ubuntu.com/. However, I have some issues trying to adjust the script. How would you go about changing the code from HttpTrigger \ __init__.py ?

I tried,

1. change __init__.py code locally
2. `docker build --tag $acr_id/selenium .`
3. `docker push $acr_id/selenium:latest`
4. `az functionapp delete (current app)`
5. az functionapp create --resource-group $rg --os-type Linux --plan $plan --deployment-container-image-name $acr_id/selenium:latest --name $fun --storage-account $stor --functions-version 2
6. ...

This procedure takes quite a lot of time, especially when trying to debug the code changes. Since I'm pretty new to docker and azure, I'm pretty sure this isn't the most effective way to adjust/debug/update the system. If you could provide any assistance, that'd be greatly appreciated.

Thank you!

**Comment by Lucifer12598** [comment]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-maven-eclipse           use this link to know about adopt and debug your azure function app

**Comment by rebremer** [comment]
Thx @Lucifer12598 , close this issue (was not aware it tbh)
